backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
site_url: https://eroyx.tk
display_url: https://eroyx.tk
logo_url: https://eroyx.tk/assets/images/favicon.png

media_folder: "assets/images"
collections:
  - label: "Global Site Settings"
    name: "site_config"
    editor:
      preview: false
    delete: false
    files:
      - label: "Metadata"
        name: "metadata"
        file: "_data/meta-data.yml"
        fields:
          - label: "Website Name"
            name: "name"
            widget: "string"
            required: true
            hint: "Ex. My Website"
          - label: "Title"
            name: "title"
            widget: "string"
            required: true
            hint: "Ex. MyWebsite"
          - label: "Description"
            name: "description"
            widget: "text"
            required: false
            hint: "This keywords will be appeared on search engines."
          - label: "Upload a Logo"
            name: "logo"
            widget: "image"
            required: true
            hint: "Upload optimized logo."
          - label: "Upload a Favicon"
            name: "favicon"
            widget: "image"
            required: false
            hint: "Upload a optimzed image."
      - label: "Menu"
        name: "menu"
        file: "_data/menus.yml"
        fields:
          - label: "Navigation Menu"
            name: "menu"
            widget: "list"
            required: false
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
                required: true
                hint: "Ex: Home"
              - label: "Link to Item"
                name: "url"
                widget: "string"
                required: true
                hint: "Ex: /home"
              - label: "Badge Label"
                name: "badge"
                widget: "string"
                required: false
                hint: "Ex: New"
      - label: "Google Adsense"
        name: "adsense"
        file: "_data/adsense.yml"
        fields:
          - label: "Status"
            name: "status"
            widget: "boolean"
            required: true
          - label: "Ad Client ID"
            name: "adsense-data-ad-client"
            widget: "string"
            required: false
            hint: "Ex. ca-pub-4944786899709076"
          - label: "Ad Slot ID"
            name: "adsense-data-ad-slot"
            widget: "string"
            required: false
            hint: "Ex.546549879894"
      - label: "Disqus Comments"
        name: "diqus_comments"
        file: "_data/disqus.yml"
        fields:
          - label: "Disqus Shortname"
            name: "disqus"
            widget: "string"
            required: false
            hint: "Ex. disqus_shortname.disqus.com"
      - label: "Mailchimp Mailing"
        name: "mailchimp_mails"
        file: "_data/mailchimp.yml"
        fields:
          - label: "Mailchimp mailing List"
            name: "mailchimp-list"
            widget: "string"
            required: false
            hint: "Ex. https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
      - label: "Google Analytics"
        name: "analytics"
        file: "_data/analytics.yml"
        fields:
          - label: "Analytics ID"
            name: "google_analytics"
            widget: "string"
            required: false
            hint: "Ex: UA-xxxxxxxx-1"
      - label: "Genre"
        name: "genre"
        file: "_data/genre.yml"
        fields:
          - label: "Genre"
            name: "genre"
            widget: "list"
            required: false
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
                required: true
                hint: "Ex. Action"
              - label: "Font Awesome icon code"
                name: "icon"
                widget: "string"
                required: true
                hint: "Ex. fas fa-snowboarding"
      - label: "Country"
        name: "country"
        file: "_data/country.yml"
        fields:
          - label: "Countries"
            name: "countries"
            widget: "list"
            required: false
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
                required: true
                hint: "Ex. India"
      - label: "Advanced Settings"
        name: "advanced_settings"
        file: "_config.yml"
        fields:
          - label: "No: of Posts in home"
            name: "paginate"
            widget: "number"
            valueType: "float"
            default: 2
            step: 1
            required: false
          - label: "Baseurl"
            name: "baseurl"
            widget: "string"
            required: true
            default: ""
  - label: "Authors"
    name: "authors"
    folder: "_authors"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    editor:
      preview: false
      delete: false
    fields:
      - label: "Shortname"
        name: "name"
        widget: "string"
        required: true
        hint: "Ex: john (Use samll letters)"
      - label: "Display Name"
        name: "display_name"
        widget: "string"
        required: true
        hint: "Ex: John Doe"
      - label: "Avatar"
        name: "avatar"
        widget: "image"
        required: false
        hint: "Use optimised images"
      - label: "Gravatar ID"
        name: "gravatar"
        widget: "string"
        required: false
        hint: "Ex: b1cc14991db7a456fcd761680bbc8f81"
      - label: "E-mail"
        name: "email"
        widget: "string"
        required: false
        hint: "Ex: john@example.com"
      - label: "Website"
        name: "web"
        widget: "string"
        required: false
        hint: "Ex: johdoe.me"
      - label: "Twitter Link"
        name: "twitter"
        widget: "string"
        required: false
        hint: "Ex: https://twitter.com/johndoe"
      - label: "About You"
        name: "description"
        widget: "text"
        required: false
  - label: "Genre"
    name: "genre"
    folder: "genre"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    editor:
      preview: false
      delete: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Ex: Action"
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
        hint: "About the genre"
  - label: "Country"
    name: "country"
    folder: "country"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    editor:
      preview: false
      delete: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Ex: India"
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
        hint: "About the country"
  - label: "Language"
    name: "language"
    folder: "language"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    editor:
      preview: false
      delete: false
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
        hint: "Ex: Malayalam"
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
        hint: "About the contents in particular language."
  - label: "Director"
    name: "director"
    folder: "director"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    editor:
      preview: false
      delete: false
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
        hint: "Ex: James Cameron"
      - label: "About"
        name: "about"
        widget: "text"
        required: false
        hint: "About the director."
  - label: "Post"
    name: "post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{title}}"
    extension: "md"
    fields:
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss"
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Post Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Ex: My First Awesome Post!"
      - label: "Thumbnail"
        name: "image"
        widget: "image"
        required: true
        hint: "Use 730*400 image."
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        required: true
        hint: "Use portrait posters."
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: [display_name]
        displayFields: [display_name]
        valueField: "name"
        required: true
        hint: "Create a author and select it."
      - label: "Genre"
        name: "genre"
        widget: "relation"
        collection: "genre"
        searchFields: [title]
        displayFields: [title]
        valueField: "title"
        required: true
        multiple: true
        hint: "Create a genre and select it."
      - label: "Country"
        name: "country"
        widget: "relation"
        collection: "country"
        searchFields: [title]
        displayFields: [title]
        valueField: "title"
        required: true
        hint: "Create a country and select it."
      - label: "Language"
        name: "language"
        widget: "relation"
        collection: "language"
        searchFields: [name]
        displayFields: [name]
        valueField: "name"
        required: false
        multiple: true
        hint: "Create a country and select it."
      - label: "Director"
        name: "director"
        widget: "relation"
        collection: "director"
        searchFields: [name]
        displayFields: [name]
        valueField: "name"
        required: false
        hint: "Create a director and select it."
      - label: "Subtitle"
        name: "subtitle"
        widget: "list"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
            hint: "Ex: Malayalam"
          - label: "File Upload"
            name: "file"
            widget: "file"
            allow_multiple: false
            media_library:
              config:
                multiple: false
            required: false
        hint: "Ex. English, Malayalam"
      - label: "Duration"
        name: "duration"
        widget: "number"
        valueType: "float"
        min: 0
        step: 1
        required: false
        hint: "Should in minutes."
      - label: "Content Rating"
        name: "content_rating"
        widget: "select"
        options:
          - { label: "5+", value: "5+" }
          - { label: "10+", value: "10+" }
          - { label: "13+", value: "13+" }
          - { label: "16+", value: "16+" }
          - { label: "18+", value: "18+" }
      - label: "Movie Rating"
        name: "rating"
        widget: "number"
        valueType: "float"
        min: 0.0
        max: 10.0
        step: 0.1
        required: false
      - label: "Release Year"
        name: "year"
        widget: "number"
        valueType: "float"
        required: false
        hint: "Ex: 2020"
      - label: "Tags"
        name: "tags"
        widget: "list"
        hint: "Tags help to find the content in search."
      - label: "Image Shadow"
        name: "imageshadow"
        widget: "boolean"
        required: false
        default: true
        hint: "Put reaction ON to show reaction buttons."
      - label: "Trailer Link"
        name: "trailer"
        widget: "string"
        required: false
        hint: "Place the youtube link of trailer."
      - label: "Streaming Link"
        name: "watch"
        widget: "string"
        required: false
        hint: "Place the link to watch the movie'"
      - label: "Telegram Download Link"
        name: "telegram"
        widget: "string"
        required: false
        hint: "Place the telegram link of movie."
      - label: "Small Description"
        name: "description"
        widget: "text"
        required: false
        hint: "This text is used by search engines."
      - label: "Review"
        name: "body"
        widget: "markdown"
